language: node_js
sudo: required
dist: trusty
addons:
  chrome: stable
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
before_script:
  - npm install -g bower polymer-cli
  - bower install
script:
  - xvfb-run npm test
